### ISSUE TITLE
using a single batch variable

### ISSUE THREAD

**Issue by dsb66** [klarman-cell-observatory/scPhere#16]
I am trying to run scPhere using a single batch variable. My batch array has the expected dimensions:
`print(batch.shape)
(31202, 1)`

scPhere fails at the training step with the following error message:
`ValueError: Cannot feed value of shape (128, 1) for Tensor 'batch_2:0', which has shape '(?,)'`

There should not be any batch_2 vector. Advice on how to proceed?
Thank you very much.

**Comment by Jerry001** [comment]
You may set the batch_id parameter this way:
batch_id=batch.iloc[:, 0].values

**Comment by dsb66** [comment]
thanks, that solved it.
